on:
  workflow_call:
    inputs:
      RELEASE_VERSION:
        description: "The version to build the package"
        required: true
        type: string

jobs:
  Build:
    name: 'Build Package'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      RELEASE_VERSION: ${{ inputs.RELEASE_VERSION }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ULTIMAKER_CI_PAT }}  # TODO: Replace with GITHUB_TOKEN - See https://ultimaker.atlassian.net/browse/EMB-120
          submodules: recursive

      - name: Build Package
        id: build
        run: |
          # BUILDTYPE is used by the build of premium firmware modules such
          # as print-process-reporting. "PRODUCTION" triggers the build of
          # an encrypted firmware module using Ultimaker/umlicensemanager.
          # Other firmware components ignore this.
          export BUILDTYPE=PRODUCTION
          export RELEASE_VERSION="${{ env.RELEASE_VERSION }}"
          echo "RELEASE_VERSION: ${RELEASE_VERSION}"
          
          # Pass encryption key directly to the build script, not as global export
          UMLM_ENCRYPTION_KEY="${{ secrets.UMLM_ENCRYPTION_KEY }}" ./build_for_ultimaker.sh -a build

      - name: Upload Artifact (Built package)
        uses: actions/upload-artifact@v4
        with:
          name: build-package
          path: "./*.deb"
