on:
  workflow_call:
    inputs:
      embedded_workflows_branch:
        description: 'Branch to checkout embedded-workflows repo'
        type: string
        required: false
        default: 'EMB-115_migrate_to_gar'  # TODO: Change to `main` once merged

jobs:
  Shellcheck:
    name: 'Shell Check'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ULTIMAKER_CI_PAT }}  # TODO: Replace with GITHUB_TOKEN - See https://ultimaker.atlassian.net/browse/EMB-120
          submodules: recursive
          fetch-depth: 0

      - name: Checkout Embedded-workflows repo
        uses: actions/checkout@v4
        with:
          repository: Ultimaker/embedded-workflows
          path: embedded-workflows
          ref: ${{ inputs.embedded_workflows_branch }}

      - name: Shell Check
        id: shellcheck
        run: |
          # Use the centralized build script from embedded-workflows
          ./embedded-workflows/scripts/build_for_ultimaker.sh -a shellcheck
